### ISSUE TITLE
(Feature request) Support `next export`

### ISSUE THREAD

**Issue by jpalpant** [styxlab/next-cms-ghost#130]
I'm a current user of [styxlab/gatsby-theme-try-ghost](https://github.com/styxlab/gatsby-theme-try-ghost) and love that project, but wanted to give Next a try. I use the gatsby repo to build a static site off of my Ghost blog, which I deploy with NGINX. I am able to get this template working (so easy! well done) but it results in a dynamic site served by node. The site works well and is beautiful, but being dynamic, it requires the Ghost deployment to be available, and is significantly more resource-intensive than the static Gatsby-built NGINX-served version. 

None of this is a concern if you use Vercel or another platform, but since I self-host, I'm interested in a static exported version of this project, if you would consider supporting it!

Next.JS supports a static export of a site with the `next export` command (this project has this available with a simple `yarn export`, but with many limitations. A few of these are 1) you can't use the default `loader` for next/image and the <Image> tag ([link](https://nextjs.org/docs/api-reference/next/image#built-in-loaders)); 2) you cannot use `getStaticPaths` with `fallback: true` ([link](https://nextjs.org/docs/basic-features/data-fetching#fallback-true))... there are probably more. 

I'm going to try to hack my way through these restrictions and see if I can't get a version working, but I'm poor at this type of development and likely won't do it cleanly if I can make it work. I'd love for this feature request to be considered so someone with more experience can make it work properly.

**Comment by styxlab** [comment]
@jpalpant Good to see you around again! I am open to making NextJS export work if you can do the heavy lifting. As you discovered already there are many places that need changes as the export imposes many restrictions.

Ideally I would like to see a new switch in appConfifg.js (that is allowed to overwrite other settings - which needs to be properly documented).

As this might be a larger task, I propose to do this with a couple of PRs that I am happy to review. The first could be to enhance the RSS switch, so that it is compatible with export when switched off.

You might have seen that I am quite busy with Blogody these days, so I see my role in reviewing and advising (making sure the changes fit into the general concept of this repo).

**Comment by HarunOr** [comment]
Hey, I just created a  PR which addresses a couple of issues you guys mentioned here, but not everything. There might be still some issues with image props, but I think it's a better solution than to manage two separate versions. 

Then again, I am not sure how you use this template, your requirements might differ from mine.
