### ISSUE TITLE
Don't manage to connect front end to headless ghost CMS.

### ISSUE THREAD

**Issue by thepartisan101** [styxlab/next-cms-ghost#15]
I must be missing an step in the guide or it might be an issue from my Ghost Cms installation, as I cannot load the content in the front end.

I have deployed the demo project on Vercel, and added environment variables (type: Plaintext ) as per this step:  
![image](https://user-images.githubusercontent.com/9511307/103796342-bf79c880-504f-11eb-8fac-b8fddba7cd12.png)

where Ghost_api_url corresponds to the URL of an existing Ghost installation on an Aws Lightsail instance.
I've created the following integration and added their values inside Vercel's environment:
![image](https://user-images.githubusercontent.com/9511307/103797257-e7b5f700-5050-11eb-9057-dbf13eea2c39.png)

I have set up Ghost to be headless by checking "Make this site private" on the CMS admin (potential issue: the password I set for accessing the site -not the admin- does not go forward, but neither do I get a "Wrong password" message).

Thanks for any help!

**Comment by styxlab** [comment]
Unless you have a typo it should work as you described. Things to check:

1. Is the demo site showing up after deploying to Vercel?
2. Are you able to reach the CMS with the above API URL from a browser (it's strange that you have an `http` and not a `https` address, those are usually used internally only).
3. If you change environment variables you may have to re-trigger a build (commit something new to your repo).

I hope you'll get it to work with the hints above, otherwise I would need your API URL and Content API Key for further debugging.

**Comment by thepartisan101** [comment]
1. Yes, here: https://next-ghost.vercel.app/
2. I can reach it, but cannot make the password that I set up work (in the "Make it private step"). I've tried creating a new integration and the API URL has HTTP as well.
3. After the initial clone the local repo couldn't push changes to remote, so I started a new project in Vercel which deployed successfully. The problem seems to come from the original Ghost CMS setup. Whenever I add the environment variables and try a new deployment, I have the following build error:
![image](https://user-images.githubusercontent.com/9511307/103872452-1bd3fb00-50d7-11eb-9d26-8599bbe821c2.png)
I suspect it's not able to fetch data from the API.
If you want to check, Content Key: 91996c0b13a7722f4c84f8a3e3, API URL: http://www.adminreports.blackswan.watch

I have the default posts data + a test post with gibberish, so no danger there.

**Comment by thepartisan101** [comment]
I've tried another step, which is according to Ghost docs here: [](https://ghost.org/docs/content-api/)

> You can upgrade your Ghost theme to use the v3 Content API by specifying the ghost-api version in the engines field of your package.json. See the handlebars reference for an example.
I've modified the package.json to include the following:
`    "engines": {
        "ghost-api": "v3"
    },`
But get the following errors during deployment:
![image](https://user-images.githubusercontent.com/9511307/103878639-5f326780-50df-11eb-8493-7e2cc0b0b944.png)
(The yellow waring seems to not have any effect from what I've read around)
![image](https://user-images.githubusercontent.com/9511307/103878759-88eb8e80-50df-11eb-948d-fa476708baa5.png)
These last errors repeat in sequence a total of 3 times. Probably not made to work with the v3 engine so I'll roll back that change.

**Comment by styxlab** [comment]
The problem is your feature image which is unreachable under

[http://3.10.58.36/content/images/2020/10/sail.jpg](http://3.10.58.36/content/images/2020/10/sail.jpg)

which causes the above shown "Failed image probe" error and inhibits a proper build.

Please either completely remove the feature image or add a new, valid image. As described in the [README](https://github.com/styxlab/next-cms-ghost#-nextjs-image-optimizations) you must also whitelist the domains from which images are served. In your case, you must add at least:

-    'www.adminreports.blackswan.watch',
-    'covid.amcharts.com',

within `next.config.js`.

**Comment by thepartisan101** [comment]
Thanks for the quick reply!

-I've removed the feature image
-Added the image domains
-Reverted the package.json changes

But the deployment still throws the same errors.

**Comment by styxlab** [comment]
I don't know what you are doing wrong, but I can now build your site with the previously given keys. So, my recommendation is to start over from scratch:

1. Clone the repository
2. Add above domains to `next.config.js` (this is just to make sure all images can be optimized, if you skip this step, it should build nonetheless)
3. Add the Ghost API URL and key to the environment variables and deploy

In case of errors, please post the full error messages here.

**Comment by thepartisan101** [comment]
Perfect, it works now!
