### ISSUE TITLE
API keys exposed

### ISSUE THREAD

**Issue by BeatPlus** [styxlab/next-cms-ghost#5]
https://github.com/styxlab/next-cms-ghost/blob/5fc7c4bee51f898bd0793fecfa6cd619c1d316f6/lib/processEnv.ts#L5-L6

There is a reference to a Ghost instance keys in the code, not sure if this was intended behavior. To follow best-practices, personal instance keys should not be included in templates.

**Comment by styxlab** [comment]
In this case, it is intended because it is the fallback mechanism pointing to a pure test installation. Unlike the Admin Key, the content API key does not expose any information beyond what is already available by visiting the test site directly, While you should not do the same for your own publication keys, it is fine for this special use case. For your own keys, use the environment variables as described in the README.

**Comment by BeatPlus** [comment]
Awesome - thanks for clarifying, closing
