### ISSUE TITLE
How to add Infinite Scroll?

### ISSUE THREAD

**Issue by Buda9** [styxlab/next-cms-ghost#59]
It's me again :) 

This time is not an issue, but a question.

After trying both next and gatsby version, my personal preference is next.js version. However, next.js version doesn't have 2 things: Infinite Scroll and lazy-loading images with blur-up effect.

Infinite Scroll would be really nice, because when 100+ posts are made, it can become a bit heavy page, like my current blog: blog(dot)vokabula(dot)com.

Or there is a way to integrate this?

**Comment by styxlab** [comment]
Hi again! 

#### Infinite scroll
`next-cms-ghost` also has infinite scroll, but it's differently implemented compared to the Gatsby version. Instead of fetching only chunks of posts on the index page, and loading more on scroll, `next-cms-ghost` takes another approch. The text for all posts is loaded on initial load, but all feature images only have placeholders. 

By using the NextJS image feature, those images are not loaded initially, but have an interaction observer attached, so they are lazy loaded on scroll. This approach is great, because the text of all posts is generally small in size compared to the images which means it's a lot faster to load text and placeholder information upfront. And the images are only loaded when scrolled into view. This works great for 100+ posts and has the advantage that you do not get any content shifts. Furthermore, it allows for ISR which would be quite difficult otherwise. If it doesn't work as expected in your use case, let me know.

#### Layzy-Loading Images with blur-up
As eluded before, images are lazy loaded here as well. Only difference to the Gatsby version is that the placeholder is just a gray space instead of a blurred image. While I also like the blur-up effect, it does have some performance impact on your site, as the blurred images are small, but larger than the empty placeholders. I expect that future versions of Next.js images will have a blur-up option. Once available, I will integrate into this repository as well.

**Comment by styxlab** [comment]
Closing as answered. We can re-open any time if needed.
