### ISSUE TITLE
QnA

### ISSUE THREAD

**Issue by khafidprayoga** [styxlab/next-cms-ghost#66]
I have some questions with this project.. where i can contact you?

**Comment by styxlab** [comment]
Questions about this project are best asked here. This is an open-source project that welcomes contributions and open discussions.

**Comment by khafidprayoga** [comment]
OK

**Comment by khafidprayoga** [comment]
I have run Ghost in my VPS, but i want to migrate using SSG workflow (Next + Ghost) where i can learn? i have no experience in javascript.

**Comment by styxlab** [comment]
The [README](https://github.com/styxlab/next-cms-ghost/blob/master/README.md) of this project is a good starting point for using Ghost with NextJS. You will have to keep your Ghost instance on your VPS and run it in headless mode as described there. To test things out, you can start by using the "Deploy" buttons directly. Just make sure to set the environment variables as described, otherwise you'll see a test page instead of your own content.

You won't get much help here regarding general learning material here. Maybe starting with the official [React docs](https://reactjs.org/tutorial/tutorial.html) is good idea - the prerequisite section also lists an [introduction to JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript).

**Comment by khafidprayoga** [comment]
Okeh
