### ISSUE TITLE
Script injection

### ISSUE THREAD

**Issue by shaderstack** [styxlab/next-cms-ghost#77]
Hi, thanks for the awesome project.

Wanted to know if script injection in header/footer is supported? I used the ghost admin UI to add script to header. But seems it doesn't get loaded when I load the website. Also, couldn't find those tags in code either. Is script injection supported?

Thanks for your time.

**Comment by styxlab** [comment]
Scripts are currently not automatically injected. The reason is that many scripts wouldn't work correctly in a React context anyways. That said, it is certainly possible to clone the project and add them to the React code in places where it makes sense (or else replace them with native React code where possible). What are the things you are doing in your scripts?

**Comment by shaderstack** [comment]
Really appreciate your reply. I'm not trying to anything fancy with external scripts atm. Just wanted to inject scripts for google analytics, code highlighting, latex support etc. But, what you say makes sense. I can just add them in code directly. Having said that, in ghost cms you have the UI to inject scripts in head/body. I'll see if I can make that work as well. Thanks again.

**Comment by mbernard** [comment]
You can take a look at my repo here
https://github.com/mbernard/next-cms-ghost

I've built some integrations, Mailchimp, prism, gtag, buyMeCoffee, etc. 

It's somewhere on my stack to open pull request for those and bring them back here at some point :P
In the meantime, Feel free to use whatever you like

**Comment by styxlab** [comment]
Closing as answered. Looking very much forward to your contributions!
