### ISSUE TITLE
Vercel hosting site couldn't catch seo meta from my own ghost installation

### ISSUE THREAD

**Issue by francolamcn** [styxlab/next-cms-ghost#81]
Hi, i have meet a tough problem with seo meta on my vercel ghost site.

I have my own ghost installation with seo meta & serp setup and it shows well on chrome tag, with title & description in home page, post, and page. however in the vercel side, every page it only shows the title (My site name, no description), and in post, it shows the title and no description neither.

How do i make a change?

**Comment by styxlab** [comment]
SEO tags should work without configuring them, so please send me the following links for further analysis:

1. Your Github repo from which you deploy your site to Vercel
2. A link to your deployed site on Vercel
3. A ling to your original Ghost site for comparsion

I might need to request more info, but that should do for a start.

**Comment by francolamcn** [comment]
Thanks for reply.
my ghost cms: https://franco.digitalpress.blog/
vercel url: https://musicdaily.vercel.app/
github repo url: https://github.com/francolamcn/franco-daily

cms home page: 
<meta name="description" content="Share the ideas, news, trends, and tools driving the new music industry &amp; everything related to music." />

Vecel home page:
<meta name="description" content="Everything About Music"/>

cms brower tag title: Mulog - everything about music
vercel brower tage title: Mulog

**Comment by styxlab** [comment]
I see, there is some misalignment for the index page. However, when I inspect a post, there is a problem in original ghost, not with Vercel:

https://musicdaily.vercel.app/portal
`meta title: Could Bruno Mars be the next Michael Jackson?`
`meta description: Bruno Mars has done really well over the past decade. He has a lot of good singles and has cemented himself as a music legend. But the thing is that he isn’t gonna reach Michael Jackson’s level at all.`

https://franco.digitalpress.blog/portal/
`meta title: Could Bruno Mars be the next Michael Jackson?` (same)
`meta description: (empty)` (missing).

In order to be able to fix the issue on the **index page**, I need the following info from you:

1. Do you have custom data in Ghost Admin -> General -> Site Meta settings? If yes, what exactly did you define there?
2. If possible, could you send me your Ghost Content API Keys (you can make a temporary one that you can delete after my testings), so it's easier for me to check your site.

Thanks for bringing this up!

**Comment by francolamcn** [comment]
yes, pls check my site meta settings: 
screenshot https://prnt.sc/12p9pzb

cms api key: cb491c7274814511dd8c63d223

**Comment by styxlab** [comment]
@all-contributors please add @francolamcn for bug

**Comment by styxlab** [comment]
Issue on index page should be fixed. Could you please test with the latest version and report back? Thanks a lot for bringing this up!

**Comment by francolamcn** [comment]
thanks a lot, it works!
meta data were crawled successfully in home page & post, pls check screenshot:
home page meta - https://prntscr.com/12ptxzf
post meta - https://prntscr.com/12ptz0q

But in tag page, it seems it grab the seo meta from home-page, check screenshot:
tag meta - https://prntscr.com/12ptyx5

**Comment by styxlab** [comment]
Should be fixed as well now.

**Comment by francolamcn** [comment]
Thanks! works fine!
