### ISSUE TITLE
Recommendation for social sharing plugin

### ISSUE THREAD

**Issue by Buda9** [styxlab/next-cms-ghost#91]
Hi styxlab, hope that Blogody is progressing nicely. Not an issue, but I have a question. What do you recommend that we use for a social sharing plugin?

**Comment by styxlab** [comment]
Hi @Buda9, good to see you here and thanks for your good wishes about Blogody - yes it is slowly progressing. 

Social sharing is a broad term, so you need to be a bit more specific ;-) What spontaneously comes to my mind is the social sharing additions that @mbernard added to his fork, have a look at  https://blog.miguelbernard.com/. Maybe you can connect and exchange ideas?

**Comment by mbernard** [comment]
Still need to be refined. It "works", but still has a few glitches. That control wasn't meant for SPA :P

The control load fine on the first page, but doesn't update afterward. Something to do with local routing in the NextJs router that doesn't trigger the refresh of the control. This has the effect of not sharing the correct link when

1. User land on your site on post1
2. Navigate to post2
3. Click share

This will share post1 instead of post2

If you can fix it, we could merge it back to styxlab repo as a new feature

**Comment by Buda9** [comment]
Thank you both!

I can think of these two possible solutions: 1. To fetch current URL from the address bar and place it inside e.g. facebook share link or 2. manually "hard code" FB share url of a current article into Post.tsx (what you probably did mbernard, since it's not refreshing).

PS. I'm just junior dev so don't expect too much help from me 😄

**Comment by styxlab** [comment]
Closing as being inactive. Can always be re-opened again. Thanks for the discussion!
